### ISSUE TITLE
Killer coda not working for k3s scenarios

### ISSUE THREAD

**Issue by narayanmurgod** [killercoda/scenarios-k3s#1]
I have been attempting to learn more about k3s. However, I am continuously encountering the error message "server IP could not be found." I have attached a screenshot of the error message.

Additionally, this is happening with other playgrounds as well (ex. Kubernetes). What could be the issue?

![Screenshot 2024-03-25 6 26 42 PM](https://github.com/killercoda/scenarios-k3s/assets/87164877/57ffcae5-2bbb-453c-8500-b54ea8045e77)
![Screenshot 2024-03-25 6 28 55 PM](https://github.com/killercoda/scenarios-k3s/assets/87164877/61909c19-2863-45a6-8833-3848c9e549a6)

**Comment by wuestkamp** [comment]
For support please contact killercoda.com/support or ask in killercoda.com/slack
